# Generated by Django 5.0.6 on 2026-09-11 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='lookbook/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Bijoux visibles sur la photo (« shoppez le look »)', related_name='lookbook_entries', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Lookbook',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymbolGuideEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex : La Croix, Le Chapelet, La Médaille miraculeuse', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='symbols/')),
                ('subtitle', models.CharField(blank=True, help_text='Courte accroche affichée sur la carte', max_length=200)),
                ('meaning', models.TextField(help_text='Signification spirituelle détaillée')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie de bijoux associée (bouton « Découvrir »)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbol_entries', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Guide des symboles',
                'ordering': ['order', 'name'],
            },
        ),
    ]
