# Generated by Django 5.0.6 on 2026-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lookbookentry_symbolguideentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_personalizable',
            field=models.BooleanField(default=False, help_text="Permet au client d'ajouter un texte de gravure/personnalisation"),
        ),
    ]
