# Generated by Django 5.0.6 on 2026-09-11 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_personalizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_preorder',
            field=models.BooleanField(default=False, help_text='Autoriser la commande même en rupture de stock (précommande)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='restock_note',
            field=models.CharField(blank=True, help_text='Ex : « Retour en stock mi-décembre »', max_length=100),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': "Liste d'attente",
                'ordering': ['-created_at'],
                'unique_together': {('variant', 'email')},
            },
        ),
    ]
