# Generated by Django 5.0.6 on 2026-09-11 14:54

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_allow_preorder_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
