# Generated by Django 5.2.18 on 2026-10-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='product_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_new'], name='product_active_new_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['notified'], name='waitlist_notified_idx'),
        ),
    ]
