# Generated by Django 5.2.18 on 2026-10-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_product_active_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/thumbs/'),
        ),
    ]
