# Generated by Django 5.1.15 on 2026-10-08 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engraving_max_chars',
            field=models.PositiveSmallIntegerField(default=30, help_text='Nombre maximum de caractères de la gravure', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='productimage',
            name='engraving_zone',
            field=models.JSONField(blank=True, help_text="Zone d'aperçu de la gravure sur cette photo (voir catalog/engraving.py)", null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='engraving_zone',
            field=models.JSONField(blank=True, help_text="Zone d'aperçu de la gravure sur la photo de cette variante", null=True),
        ),
    ]
