# Generated by Django 5.1.15 on 2026-10-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_engraving_zones'),
        ('notifications', '0003_verseoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='contacted',
            field=models.BooleanField(default=False, help_text='Relancée à la main (WhatsApp ou appel)'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='push_notified',
            field=models.BooleanField(default=False, help_text='Notification de retour en stock envoyée'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='push_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.pushsubscription'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='notified',
            field=models.BooleanField(default=False, help_text='E-mail de retour en stock envoyé'),
        ),
    ]
