# Generated by Django 5.1.15 on 2026-10-08 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_verseoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('perm', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=200)),
                ('url', models.CharField(default='/', max_length=200)),
                ('emailed', models.BooleanField(default=False)),
                ('pushed', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['done_at', 'created_at'], name='alert_queue_idx')],
            },
        ),
    ]
