# Generated by Django 5.0.6 on 2026-09-11 14:10

import django.db.models.deletion
import orders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_email_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='engraving_text',
            field=models.CharField(blank=True, help_text='Texte de gravure/personnalisation', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant déduit via la carte cadeau', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='engraving_text',
            field=models.CharField(blank=True, help_text='Texte de gravure/personnalisation', max_length=60),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=orders.models.generate_giftcard_code, editable=False, max_length=30, unique=True)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaser_name', models.CharField(blank=True, max_length=200)),
                ('purchaser_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('active', 'Active'), ('used', 'Épuisée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.OneToOneField(help_text='Commande via laquelle cette carte a été achetée et payée', on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_purchase', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card',
            field=models.ForeignKey(blank=True, help_text='Carte cadeau utilisée pour régler (tout ou partie de) cette commande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_in_orders', to='orders.giftcard'),
        ),
    ]
