# Generated by Django 5.0.6 on 2026-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_loyalty_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='reason',
            field=models.CharField(choices=[('earned', 'Points gagnés'), ('redeemed', 'Points utilisés'), ('referral', 'Parrainage'), ('adjusted', 'Ajustement manuel')], max_length=20),
        ),
    ]
