# Generated by Django 5.1.15 on 2026-10-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_image_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('add_to_carts', models.PositiveIntegerField(default=0)),
                ('checkouts', models.PositiveIntegerField(default=0)),
                ('viewers', models.PositiveIntegerField(default=0)),
                ('carters', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('devices', models.JSONField(default=dict)),
                ('sources', models.JSONField(default=dict)),
                ('pages', models.JSONField(default=dict)),
                ('searches', models.JSONField(default=dict)),
                ('empty_searches', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=36, unique=True)),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('browser', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('landing_path', models.CharField(blank=True, max_length=200)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('adds', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='dps_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'product'), name='unique_daily_product')],
            },
        ),
        migrations.CreateModel(
            name='TrackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pageview', 'Page vue'), ('product_view', 'Fiche produit vue'), ('add_to_cart', 'Ajout au panier'), ('remove_from_cart', 'Retrait du panier'), ('favorite_add', 'Ajout aux favoris'), ('favorite_remove', 'Retrait des favoris'), ('search', 'Recherche'), ('begin_checkout', 'Début de commande')], max_length=20)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('ref', models.CharField(blank=True, max_length=80)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitsession')),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'created_at'], name='track_type_date_idx')],
            },
        ),
    ]
