# Generated by Django 5.0.6 on 2026-09-09 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffrets/')),
                ('box_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix du contenant, hors articles choisis', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffretConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coffret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='coffrets.coffret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffretSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Ex: Choisissez un collier', max_length=200)),
                ('min_select', models.PositiveSmallIntegerField(default=1)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('allowed_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffret_slots', to='catalog.category')),
                ('coffret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='coffrets.coffret')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoffretConfigurationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffrets.coffretconfiguration')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coffret_items', to='catalog.productvariant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chosen_items', to='coffrets.coffretslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
