# Generated by Django 5.0.6 on 2026-09-11 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_enable_pg_trgm'),
        ('coffrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffret',
            name='allow_customization',
            field=models.BooleanField(default=True, help_text="La cliente peut-elle retirer des éléments inclus ou en ajouter d'autres ?"),
        ),
        migrations.AddField(
            model_name='coffret',
            name='show_contents',
            field=models.BooleanField(default=True, help_text='La cliente voit-elle le détail du contenu du coffret ?'),
        ),
        migrations.AddField(
            model_name='coffret',
            name='show_item_prices',
            field=models.BooleanField(default=True, help_text='Afficher le prix de chaque élément (sinon seul le prix total du coffret est visible)'),
        ),
        migrations.AlterField(
            model_name='coffretconfigurationitem',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Vide si ajouté librement par la cliente (hors emplacement prédéfini)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chosen_items', to='coffrets.coffretslot'),
        ),
        migrations.CreateModel(
            name='CoffretItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('coffret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='coffrets.coffret')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coffret_inclusions', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='coffretconfiguration',
            name='removed_items',
            field=models.ManyToManyField(blank=True, help_text='Éléments inclus par défaut que la cliente a retirés', related_name='removed_in_configurations', to='coffrets.coffretitem'),
        ),
    ]
