# Generated by Django 5.0.6 on 2026-09-11 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import get_random_string


def backfill_referral_codes(apps, schema_editor):
    User = apps.get_model('userauths', 'User')
    used = set()
    for user in User.objects.all():
        code = get_random_string(8, allowed_chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789')
        while code in used:
            code = get_random_string(8, allowed_chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789')
        used.add(code)
        user.referral_code = code
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=12, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_rewarded',
            field=models.BooleanField(default=False, help_text='Le parrain a déjà été récompensé pour ce filleul'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
