# Generated by Django 5.1.15 on 2026-10-08 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_referral_code_user_referral_rewarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='support', max_length=20)),
                ('extra_permissions', models.JSONField(blank=True, default=dict, help_text='Ajustements individuels : {droit: true/false}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(help_text="E-mail au moment de l'action (reste lisible si le compte est supprimé)", max_length=254)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=12)),
                ('summary', models.CharField(max_length=300)),
                ('object_type', models.CharField(blank=True, max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_actor_date_idx')],
            },
        ),
    ]
