# Generated by Django 5.1.15 on 2026-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_staff_profile_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='commune',
            field=models.CharField(blank=True, help_text="Commune d'Abidjan (liste fixe) ; vide hors d'Abidjan", max_length=40),
        ),
        migrations.AddField(
            model_name='address',
            name='quartier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text="Rue, repères, indications d'accès", max_length=255),
        ),
    ]
