# Generated by Django 5.1.15 on 2026-10-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_address_commune_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_seen_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle la personne a terminé ou passé le didactiel de l'Admin", null=True),
        ),
    ]
