# Generated by Django 5.1.15 on 2026-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(blank=True, default="Livraison rapide en Côte d'Ivoire · Emballage cadeau offert · Paiement sécurisé", max_length=200)),
                ('hero_kicker', models.CharField(blank=True, default='Bijoux & objets chrétiens', max_length=80)),
                ('hero_title', models.CharField(blank=True, default='Porte ta foi avec élégance', max_length=80)),
                ('hero_text', models.CharField(blank=True, default='Des bijoux et objets chrétiens pensés pour accompagner votre foi au quotidien.', max_length=250)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_text', models.CharField(blank=True, default='Des bijoux et objets de piété pensés pour accompagner votre foi, au quotidien comme dans les grands moments.', max_length=250)),
                ('tagline', models.CharField(blank=True, default='Chaque vision mérite de voir le jour', max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='support@monarmoire.store', max_length=254)),
                ('phone', models.CharField(blank=True, default='+225 07 99 16 73 93', max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text="Chiffres seulement, avec l'indicatif (ex : 2250799167393)", max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, default="Abidjan, Côte d'Ivoire", max_length=80)),
                ('terms_text', models.TextField(blank=True, help_text='Conditions générales de vente (texte simple)', max_length=30000)),
                ('privacy_text', models.TextField(blank=True, help_text='Politique de confidentialité (texte simple)', max_length=30000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Réglages du site',
            },
        ),
    ]
