# Generated by Django 5.1.15 on 2026-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Adresse (privée) qui reçoit aussi les alertes : nouvelle commande, stock bas, nouvel avis', max_length=254),
        ),
    ]
